//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldAlliance.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TermDeposit
    {
        public int TermDepositId { get; set; }
        public int MemberId { get; set; }

        [Required]
        [Range(1000.00, double.MaxValue, ErrorMessage = "Term Deposit must have minimum amount of $1000.00")]
        public decimal Amount { get; set; }

        [Required]
        [Range(6, int.MaxValue, ErrorMessage = "Duration must be at least 6 months")]
        public int Duration_Months { get; set; }

        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime StartDate { get; set; }

        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
