//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldAlliance.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public int TransTypeId { get; set; }
        public int AccountNumber { get; set; }
        public Nullable<int> AccountForTransfer { get; set; }

        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime TransactionDate { get; set; }

        [Range(1, double.MaxValue, ErrorMessage = "Amount must be a positive value")]
        public decimal Amount { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
